### ISSUE TITLE
Implement Lightstep support for reports

### ISSUE THREAD

**Issue by andrerpena** [zalando-zmon/zmon-slo-metrics#163]
Implement Lightstep as a source for generating SLO reports

### TODO:
- [x] Be able to install the SLR tool dependencies, even though they only work with Python 3.6 - Done, thanks to Mohab
- [ ] Be able to properly run the application locally https://github.com/zalando-zmon/service-level-reporting/issues/164
- [x] Read the Lightstep API documentation https://app.lightstep.com/Production/service-directory/a-proxy/operations
- [x] Get a Lightstep API user

**Comment by andrerpena** [comment]
Please assign it to me :)
